<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>488</string>
    </array>
    <key>name</key>
    <string>488</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>(=|&lt;|&lt;=|&gt;|&gt;=)</string>
            <key>name</key>
            <string>keyword.operator.comparison.488</string>
        </dict>

        <dict>
            <key>match</key>
            <string>(\+|-|\*|\/)</string>
            <key>name</key>
            <string>keyword.operator.arithemic.488</string>
        </dict>

        <dict>
            <key>match</key>
            <string>\b(if|else|then|repeat|until|while|do|exit|not|when)\b</string>
            <key>name</key>
            <string>keyword.control.flow.488</string>
        </dict>

        <dict>
            <key>match</key>
            <string>:=</string>
            <key>name</key>
            <string>keyword.operator.assignment.488</string>
        </dict>

        <dict>
            <key>match</key>
            <string>\b(and|or|not)\b</string>
            <key>name</key>
            <string>keyword.operator.logical.488</string>
        </dict>

        <dict>
            <key>match</key>
            <string>\b(var)\b</string>
            <key>name</key>
            <string>storage.type.488</string>
        </dict>

        <dict>
            <key>match</key>
            <string>\b(newline|:)\b</string>
            <key>name</key>
            <string>keyword.control.488</string>
        </dict>

        <dict>
            <key>match</key>
            <string>\b(read|write)\b</string>
            <key>name</key>
            <string>keyword.other.io.488</string>
        </dict>


        <dict>
            <key>match</key>
            <string>\b(return\s*(with)?)\b</string>
            <key>name</key>
            <string>keyword.control.flow.return.488</string>
        </dict>


        <dict>
            <key>match</key>
            <string>\b(Integer|Boolean)\b</string>
            <key>name</key>
            <string>support.type.488</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(true|false)\b</string>
            <key>name</key>
            <string>constant.language.boolean.488</string>
        </dict>

        <dict>
            <key>begin</key>
            <string>(function|procedure)\s*\w*</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.function.488</string>
                </dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.488</string>
                </dict>
            </dict>
            <key>end</key>
            <string>{</string>
            <key>name</key>
            <string>meta.function.488</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(Integer|Boolean)</string>
                    <key>name</key>
                    <string>support.type.488</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\w*</string>
                    <key>name</key>
                    <string>variable.parameter.488</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>:|,</string>
                    <key>name</key>
                    <string>punctuation.separator.annotation.parameter.488</string>
                </dict>
            </array>
        </dict>

        <dict>
            <key>begin</key>
            <string>(\w*)(\()</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.488</string>
                </dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.arguments.begin.488</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.arguments.end.488</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.function.488</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(Integer|Boolean)</string>
                    <key>name</key>
                    <string>support.type.488</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\w*</string>
                    <key>name</key>
                    <string>variable.parameter.488</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>,</string>
                    <key>name</key>
                    <string>punctuation.separator.annotation.parameter.488</string>
                </dict>
            </array>
        </dict>

        <dict>
            <key>begin</key>
            <string>%</string>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>comment.line.488</string>
            <key>patterns</key>
            <array/>
        </dict>
        <dict>
            <key>match</key>
            <string>\b\d*\b</string>
            <key>name</key>
            <string>constant.numeric.488</string>
        </dict>
        <dict>
            <key>match</key>
            <string>"[^"]*"</string>
            <key>name</key>
            <string>string.488</string>
        </dict>
    </array>
    <key>repository</key>
    <dict/>
    <key>scopeName</key>
    <string>source.488</string>
    <key>uuid</key>
    <string>07629b98-022c-4204-a227-aa65ae352fab</string>
</dict>
</plist>
